language: node_js
node_js:
  - "6"
stages:
  - name: deploy
    # require the branch name to be master
    if: branch = master
before_script:
  - npm install
script: 
  - ./node_modules/.bin/gulp build --mix --itowns --ol3
  - ./node_modules/.bin/gulp build --leaflet
cache:
  directories:
    - node_modules
before_deploy:
    - git clone https://github.com/IGNF/geoportal-extensions --branch gh-pages deploy/
    - cp -r target/build/Itowns/dist deploy/bundles/
    - cp -r target/build/Mix/dist deploy/bundles/
    - cp -r target/build/Ol3/dist deploy/bundles/
    - cp -r target/build/Leaflet/dist deploy/bundles/
    - mkdir deploy/doc/
    - cp -r target/build/Leaflet/doc deploy/doc/leaflet/
    - cp -r target/build/Ol3/doc deploy/doc/ol3/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $ghkey  # Set in travis-ci.org dashboard, marked secure
  local_dir: deploy/
  keep-history: true
  on:
    branch: master
  after_deploy:
    - rm -rf deploy/
